version: "3.9"
services:
  api:
    build:
      context: ./
      dockerfile: Api/Dockerfile
    image: mentor-api:latest
    container_name: mentor-api
    restart: always
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    env_file:
      - secrets/secrets.env
